-- Optional Seed Data File (Cleared)
-- To ensure a 100% clean database with zero mock users, AI bots, or fake chats,
-- this file is left blank. All users shown in your UI will be real accounts 
-- that sign up through the registration screens.
